import Mathlib

set_option linter.style.header false

/-!
# Shevelev's Theorem 1: closed formulas via root-of-unity filters

Formalization of Theorem 1 (formulas (8), (9)) of V. Shevelev, *Combinatorial identities
generated by difference analogs of hyperbolic and trigonometric functions of order n*,
arXiv:1706.01454v4 [math.CO], 2017.  `README.md` gives the equational derivation.

With `r = s - 1`, the paper's difference analogs `H_s(m, n)` and `K_s(m, n)` are the sums
`∑ k ∈ range (m + 1), if (n : ℤ) ∣ k - r then … else 0` below, and its factor `ω ^ (-j * r)`
is written `(ω ^ j) ^ (-r)`.  Both closed formulas are instances of one filter lemma,
`sum_geom_pow`, over the family `x j = b * q ^ j`: `(b, q) = (1, ω)` yields `H`, and
`(b, q) = (μ, μ ^ 2)` yields `K`.
-/

namespace Shevelev

open Finset

/-- **Root-of-unity filter.** For `q` a primitive `n`-th root of unity and `b ≠ 0`,
expanding `(b * q ^ j + 1) ^ m` and summing over `j < n` annihilates every binomial
term except those with `n ∣ k - r`, each surviving with weight `n * b ^ (k - r)`. -/
theorem sum_geom_pow (n : ℕ) (hn : 0 < n) {b q : ℂ} (hb : b ≠ 0)
    (hq : IsPrimitiveRoot q n) (r : ℤ) (m : ℕ) :
    ∑ j ∈ range n, (b * q ^ j + 1) ^ m * (b * q ^ j) ^ (-r)
      = n * ∑ k ∈ range (m + 1),
          if (n : ℤ) ∣ (k : ℤ) - r then b ^ ((k : ℤ) - r) * (m.choose k : ℂ) else 0 := by
  have hq0 : q ≠ 0 := hq.ne_zero hn.ne'
  -- Binomial expansion, shifted by `-r`.
  have hterm : ∀ x : ℂ, x ≠ 0 → (x + 1) ^ m * x ^ (-r)
      = ∑ k ∈ range (m + 1), x ^ ((k : ℤ) - r) * (m.choose k : ℂ) := fun x hx => by
    rw [add_pow, sum_mul]
    exact sum_congr rfl fun k _ => by
      rw [one_pow, mul_one, sub_eq_add_neg, zpow_add₀ hx, zpow_natCast]; ring
  -- The filter itself: `∑_{j < n} q ^ (j * a)` detects `n ∣ a`.
  have hfil : ∀ a : ℤ, ∑ j ∈ range n, q ^ ((j : ℤ) * a)
      = if (n : ℤ) ∣ a then (n : ℂ) else 0 := by
    intro a
    have h : ∀ j : ℕ, q ^ ((j : ℤ) * a) = (q ^ a) ^ j := fun j => by
      rw [mul_comm, zpow_mul, zpow_natCast]
    simp only [h]
    by_cases hd : (n : ℤ) ∣ a
    · simp [hd, (hq.zpow_eq_one_iff_dvd a).mpr hd]
    · rw [geom_sum_eq fun hc => hd ((hq.zpow_eq_one_iff_dvd a).mp hc),
        show (q ^ a) ^ n = 1 by rw [← zpow_natCast (q ^ a) n, ← zpow_mul, mul_comm, zpow_mul,
          zpow_natCast, hq.pow_eq_one, one_zpow], sub_self, zero_div, if_neg hd]
  calc ∑ j ∈ range n, (b * q ^ j + 1) ^ m * (b * q ^ j) ^ (-r)
      = ∑ j ∈ range n, ∑ k ∈ range (m + 1),
          b ^ ((k : ℤ) - r) * (m.choose k : ℂ) * q ^ ((j : ℤ) * ((k : ℤ) - r)) :=
        sum_congr rfl fun j _ =>
          (hterm _ (mul_ne_zero hb (pow_ne_zero j hq0))).trans <| sum_congr rfl fun k _ => by
            rw [mul_zpow, ← zpow_natCast q j, ← zpow_mul]; ring
    _ = n * ∑ k ∈ range (m + 1),
          if (n : ℤ) ∣ (k : ℤ) - r then b ^ ((k : ℤ) - r) * (m.choose k : ℂ) else 0 := by
        rw [sum_comm, mul_sum]
        exact sum_congr rfl fun k _ => by rw [← mul_sum, hfil]; split_ifs <;> ring

/-- **Formula (8)** for any primitive `n`-th root of unity `ω`, with `r = s - 1`. -/
theorem theorem1_H (n : ℕ) (hn : 0 < n) {ω : ℂ} (hω : IsPrimitiveRoot ω n) (r : ℤ) (m : ℕ) :
    ∑ j ∈ range n, (ω ^ j + 1) ^ m * (ω ^ j) ^ (-r)
      = n * ∑ k ∈ range (m + 1), if (n : ℤ) ∣ (k : ℤ) - r then (m.choose k : ℂ) else 0 := by
  simpa only [one_mul, one_zpow] using sum_geom_pow n hn one_ne_zero hω r m

/-- **Formula (9)** for `μ ≠ 0` with `μ ^ n = -1` and `μ ^ 2` a primitive `n`-th root. -/
theorem theorem1_K (n : ℕ) (hn : 0 < n) {μ : ℂ} (hμ0 : μ ≠ 0) (hμn : μ ^ n = -1)
    (hμ2 : IsPrimitiveRoot (μ ^ 2) n) (r : ℤ) (m : ℕ) :
    ∑ j ∈ range n, (μ ^ (2 * j + 1) + 1) ^ m * (μ ^ (2 * j + 1)) ^ (-r)
      = n * ∑ k ∈ range (m + 1), if (n : ℤ) ∣ (k : ℤ) - r then
          (if Even (((k : ℤ) - r) / (n : ℤ)) then 1 else -1) * (m.choose k : ℂ) else 0 := by
  have hn0 : (n : ℤ) ≠ 0 := Nat.cast_ne_zero.2 hn.ne'
  -- On a divisible term `μ ^ (k - r)` collapses to a sign, because `μ ^ n = -1`.
  have hpow : ∀ a : ℤ, (n : ℤ) ∣ a → μ ^ a = if Even (a / (n : ℤ)) then 1 else -1 := by
    rintro a ⟨t, rfl⟩
    rw [Int.mul_ediv_cancel_left _ hn0, zpow_mul, zpow_natCast, hμn]
    rcases Int.even_or_odd t with h | h
    · rw [if_pos h, h.neg_one_zpow]
    · rw [if_neg (Int.not_even_iff_odd.2 h), h.neg_one_zpow]
  calc ∑ j ∈ range n, (μ ^ (2 * j + 1) + 1) ^ m * (μ ^ (2 * j + 1)) ^ (-r)
      = ∑ j ∈ range n, (μ * (μ ^ 2) ^ j + 1) ^ m * (μ * (μ ^ 2) ^ j) ^ (-r) :=
        sum_congr rfl fun j _ => by
          rw [show μ * (μ ^ 2) ^ j = μ ^ (2 * j + 1) by rw [← pow_mul, pow_succ]; ring]
    _ = n * ∑ k ∈ range (m + 1),
          if (n : ℤ) ∣ (k : ℤ) - r then μ ^ ((k : ℤ) - r) * (m.choose k : ℂ) else 0 :=
        sum_geom_pow n hn hμ0 hμ2 r m
    _ = _ := by
        congr 1
        refine sum_congr rfl fun k _ => ?_
        by_cases hd : (n : ℤ) ∣ (k : ℤ) - r
        · rw [if_pos hd, if_pos hd, hpow _ hd]
        · rw [if_neg hd, if_neg hd]

/-- **Formula (8)** at the standard root `ω = exp (2 π i / n)`. -/
theorem theorem1_H_exp (n : ℕ) (hn : 0 < n) (r : ℤ) (m : ℕ) :
    ∑ k ∈ range (m + 1), (if (n : ℤ) ∣ (k : ℤ) - r then (m.choose k : ℂ) else 0)
      = (n : ℂ)⁻¹ * ∑ j ∈ range n, (Complex.exp (2 * Real.pi * Complex.I / n) ^ j + 1) ^ m
          * (Complex.exp (2 * Real.pi * Complex.I / n) ^ j) ^ (-r) := by
  rw [theorem1_H n hn (Complex.isPrimitiveRoot_exp n hn.ne') r m,
    inv_mul_cancel_left₀ (Nat.cast_ne_zero.2 hn.ne' : (n : ℂ) ≠ 0)]

/-- **Formula (9)** at the standard root `μ = exp (π i / n)`, which satisfies `μ ^ n = -1`. -/
theorem theorem1_K_exp (n : ℕ) (hn : 0 < n) (r : ℤ) (m : ℕ) :
    ∑ k ∈ range (m + 1), (if (n : ℤ) ∣ (k : ℤ) - r then
        (if Even (((k : ℤ) - r) / (n : ℤ)) then 1 else -1) * (m.choose k : ℂ) else 0)
      = (n : ℂ)⁻¹ * ∑ j ∈ range n,
          (Complex.exp (Real.pi * Complex.I / n) ^ (2 * j + 1) + 1) ^ m
            * (Complex.exp (Real.pi * Complex.I / n) ^ (2 * j + 1)) ^ (-r) := by
  have hn0 : (n : ℂ) ≠ 0 := Nat.cast_ne_zero.2 hn.ne'
  have hμn : Complex.exp (Real.pi * Complex.I / n) ^ n = -1 := by
    rw [← Complex.exp_nat_mul,
      show (n : ℂ) * (Real.pi * Complex.I / n) = Real.pi * Complex.I by field_simp,
      Complex.exp_pi_mul_I]
  have hμ2 : IsPrimitiveRoot (Complex.exp (Real.pi * Complex.I / n) ^ 2) n := by
    rw [← Complex.exp_nat_mul, show ((2 : ℕ) : ℂ) * (Real.pi * Complex.I / n)
      = 2 * Real.pi * Complex.I / n by push_cast; ring]
    exact Complex.isPrimitiveRoot_exp n hn.ne'
  rw [theorem1_K n hn (Complex.exp_ne_zero _) hμn hμ2 r m, inv_mul_cancel_left₀ hn0]

end Shevelev
