import Mathlib

-- This is a standalone project rather than a Mathlib file, so it carries no
-- Mathlib copyright header; the rest of the `mathlibStandardSet` linters are on.
set_option linter.style.header false

/-!
# Combinatorial identities from difference analogs of hyperbolic and trigonometric functions

A Lean 4 / Mathlib formalization of

  Vladimir Shevelev, *Combinatorial identities generated by difference analogs of
  hyperbolic and trigonometric functions of order n*, arXiv:1706.01454v4 [math.CO].

## Dictionary with the paper

Indices are shifted by one (`r = s - 1`), which makes every statement cleaner:

| paper                     | here                                                 |
| ------------------------- | ---------------------------------------------------- |
| `H_s(m,n)`, formula (13)  | `H n (s-1) m = F n 1 (s-1) m`                        |
| `K_s(m,n)`, formula (14)  | `K n (s-1) m = F n (-1) (s-1) m`                     |
| extension (10)            | `F_add_natCast` : `F n ε (r+n) m = ε * F n ε r m`    |
| systems (6),(7)           | `F_succ` : `F n ε r (m+1) = F n ε r m + F n ε (r-1) m` |
| wrap-around `Δy₁ = ±yₙ`   | `H_delta_one` / `K_delta_one`                        |
| Theorem 1, (8)/(9)        | `theorem1_H` / `theorem1_K` (any primitive root)     |
| (8)/(9) at the paper's roots | `theorem1_H_exp` / `theorem1_K_exp`               |
| Theorem 2, (11)/(12)      | `theorem2_H` / `theorem2_K`                          |
| Theorem 3, eigenvalue     | `altRowSum_H` / `altRowSum_K`                        |
| Theorem 3, determinant    | `det_circulant_H` / `det_circulant_K`                |

Formulas (13),(14) are taken as the *definition* of `H` and `K`; the fact that they
solve the difference systems of Definitions 3 and 4 (which is the paper's Section 2
opening remark, `Δ C(m,k) = C(m,k-1)`) is the lemma `F_succ` together with
`F_zero_nat`. Everything is proved for a single family `F n ε` with `ε * ε = 1`,
so `H` (`ε = 1`) and `K` (`ε = -1`) are handled at once — exactly the paper's
observation that "the proofs for the formulas of Theorem 2 are identical".

The core development compiles sorry-free with Lean 4.30.0 / Mathlib v4.30.0. The
six `paper_*` bridge goals at the end restate the paper's exact printed formulas
and are deliberately left as `sorry` (so `lake build` emits six such warnings).
-/

namespace Shevelev

open Finset

/-! ## 1. A `±1`-valued exponential -/

/-- `mark ε q` is `ε ^ q` when `ε = ±1`, defined for *all* integers `q`
(the paper's `(-1)^t`, where `t` may be thought of as ranging over `ℤ`). -/
def mark (ε : ℤ) (q : ℤ) : ℤ := if Even q then 1 else ε

@[simp] lemma mark_zero (ε : ℤ) : mark ε 0 = 1 := by simp [mark]

@[simp] lemma mark_one_eq (q : ℤ) : mark 1 q = 1 := by
  unfold mark; split <;> rfl

lemma mark_natCast_neg (t : ℕ) : mark (-1) (t : ℤ) = (-1 : ℤ) ^ t := by
  rcases Nat.even_or_odd t with h | h
  · rw [mark, if_pos (by exact_mod_cast h : Even ((t : ℤ))), h.neg_one_pow]
  · have h' : ¬ Even ((t : ℤ)) := by
      simpa [Int.not_even_iff_odd] using (by exact_mod_cast h : Odd ((t : ℤ)))
    rw [mark, if_neg h', h.neg_one_pow]

lemma mark_add_one {ε : ℤ} (hε : ε * ε = 1) (q : ℤ) : mark ε (q + 1) = ε * mark ε q := by
  rcases Int.even_or_odd q with h | h
  · have h' : ¬ Even (q + 1) := by simp [h]
    simp only [mark, if_pos h, if_neg h', mul_one]
  · have h1 : ¬ Even q := by simpa [Int.not_even_iff_odd] using h
    have h2 : Even (q + 1) := by simpa [Int.even_add_one] using h1
    simp only [mark, if_neg h1, if_pos h2]
    exact hε.symm

lemma mark_sub_one {ε : ℤ} (hε : ε * ε = 1) (q : ℤ) : mark ε (q - 1) = ε * mark ε q := by
  have h := mark_add_one hε (q - 1)
  have hq : q - 1 + 1 = q := by ring
  rw [hq] at h
  rw [h, ← mul_assoc, hε, one_mul]

/-! ## 2. The difference analogs

`F n ε r m = ∑_{t} ε^t * C(m, n*t + r)`, written as a sum over `k = n*t + r ≤ m`. -/

/-- Coefficient of `C(m,k)` in `F n ε r m`: it is `ε ^ t` if `k = n * t + r`, else `0`. -/
def coef (n : ℕ) (ε : ℤ) (r : ℤ) (k : ℕ) : ℤ :=
  if (n : ℤ) ∣ ((k : ℤ) - r) then mark ε (((k : ℤ) - r) / (n : ℤ)) else 0
-- Decidability of `(n : ℤ) ∣ ·` keeps `coef`, `F`, `H`, `K` computable, so the
-- sanity checks in §6 go through by `decide`.

/-- The common generalization of formulas (13) and (14) of the paper. -/
def F (n : ℕ) (ε : ℤ) (r : ℤ) (m : ℕ) : ℤ :=
  ∑ k ∈ range (m + 1), coef n ε r k * (m.choose k : ℤ)

/-- Difference hyperbolic function of order `n`: `H n (s-1) m = H_s(m,n)`, formula (13). -/
def H (n : ℕ) (r : ℤ) (m : ℕ) : ℤ := F n 1 r m

/-- Difference trigonometric function of order `n`: `K n (s-1) m = K_s(m,n)`, formula (14). -/
def K (n : ℕ) (r : ℤ) (m : ℕ) : ℤ := F n (-1) r m

lemma H_eq (n : ℕ) (r : ℤ) (m : ℕ) :
    H n r m = ∑ k ∈ range (m + 1), (if (n : ℤ) ∣ ((k : ℤ) - r) then (m.choose k : ℤ) else 0) := by
  rw [H, F]
  refine Finset.sum_congr rfl fun k _ => ?_
  simp only [coef, mark_one_eq]
  split_ifs <;> ring

/-- Shifting the residue by one is the same as shifting `k` by one. -/
lemma coef_succ (n : ℕ) (ε : ℤ) (r : ℤ) (k : ℕ) : coef n ε r (k + 1) = coef n ε (r - 1) k := by
  have h : ((k + 1 : ℕ) : ℤ) - r = (k : ℤ) - (r - 1) := by push_cast; ring
  simp only [coef, h]

@[simp] lemma F_zero (n : ℕ) (ε : ℤ) (r : ℤ) : F n ε r 0 = coef n ε r 0 := by
  simp [F]

/-- The initial conditions of Definitions 3 and 4: `y_1(0) = 1`, `y_s(0) = 0` for `s ≠ 1`. -/
lemma F_zero_nat (n : ℕ) (ε : ℤ) (hn : 0 < n) {b : ℕ} (hb : b < n) :
    F n ε (b : ℤ) 0 = if b = 0 then 1 else 0 := by
  rw [F_zero]
  by_cases h : b = 0
  · subst h; simp [coef]
  · have hb0 : 0 < (b : ℤ) := by exact_mod_cast Nat.pos_of_ne_zero h
    have hbn : (b : ℤ) < (n : ℤ) := by exact_mod_cast hb
    have hn' : (0 : ℤ) < (n : ℤ) := by exact_mod_cast hn
    have hd : ¬ ((n : ℤ) ∣ (((0 : ℕ) : ℤ) - (b : ℤ))) := by
      rintro ⟨q, hq⟩
      simp only [Nat.cast_zero, zero_sub] at hq
      rcases lt_trichotomy q 0 with hq0 | hq0 | hq0
      · have : q ≤ -1 := by omega
        nlinarith
      · rw [hq0, mul_zero] at hq; omega
      · nlinarith
    simp only [coef, if_neg h]
    exact if_neg hd

/-- **The difference equations (6) and (7)**: `Δ y_s = y_{s-1}`.
This is the paper's `Δ C(m,k) = C(m,k-1)`, i.e. Pascal's rule. -/
theorem F_succ (n : ℕ) (ε : ℤ) (r : ℤ) (m : ℕ) :
    F n ε r (m + 1) = F n ε r m + F n ε (r - 1) m := by
  have hchoose : ∀ k : ℕ,
      (((m + 1).choose (k + 1) : ℕ) : ℤ) = (m.choose k : ℤ) + (m.choose (k + 1) : ℤ) := by
    intro k
    exact_mod_cast congrArg (fun x : ℕ => (x : ℤ)) (Nat.choose_succ_succ m k)
  have e1 : F n ε r (m + 1)
      = (∑ k ∈ range (m + 1), coef n ε r (k + 1) * (((m + 1).choose (k + 1) : ℕ) : ℤ))
        + coef n ε r 0 := by
    rw [F, Finset.sum_range_succ'
      (fun k => coef n ε r k * (((m + 1).choose k : ℕ) : ℤ)) (m + 1)]
    simp
  have e2 : ∀ k : ℕ, coef n ε r (k + 1) * (((m + 1).choose (k + 1) : ℕ) : ℤ)
      = coef n ε (r - 1) k * (m.choose k : ℤ)
        + coef n ε r (k + 1) * (m.choose (k + 1) : ℤ) := by
    intro k
    rw [hchoose k, mul_add, coef_succ]
  have e3 : (∑ k ∈ range (m + 1), coef n ε r (k + 1) * (m.choose (k + 1) : ℤ))
      = F n ε r m - coef n ε r 0 := by
    rw [Finset.sum_range_succ, F,
      Finset.sum_range_succ' (fun k => coef n ε r k * (m.choose k : ℤ)) m]
    simp [mul_comm]
  rw [e1]
  simp only [e2]
  rw [Finset.sum_add_distrib, e3, ← F]
  ring

/-- **Formula (10)**: the natural extension of `H` and `K` outside `s ∈ {1,…,n}`.
For `ε = 1` this says `H` is `n`-periodic, for `ε = -1` that `K` is `n`-antiperiodic. -/
theorem F_add_natCast (n : ℕ) {ε : ℤ} (hε : ε * ε = 1) (hn : 0 < n) (r : ℤ) (m : ℕ) :
    F n ε (r + n) m = ε * F n ε r m := by
  have hn' : (n : ℤ) ≠ 0 := by exact_mod_cast hn.ne'
  have key : ∀ k : ℕ, coef n ε (r + n) k = ε * coef n ε r k := by
    intro k
    by_cases h : (n : ℤ) ∣ ((k : ℤ) - r)
    · obtain ⟨q, hq⟩ := h
      have h2 : (k : ℤ) - (r + (n : ℤ)) = (n : ℤ) * (q - 1) := by linear_combination hq
      have hdvd : (n : ℤ) ∣ ((k : ℤ) - (r + (n : ℤ))) := ⟨q - 1, h2⟩
      rw [coef, coef, if_pos hdvd, if_pos ⟨q, hq⟩, hq, h2,
        Int.mul_ediv_cancel_left _ hn', Int.mul_ediv_cancel_left _ hn', mark_sub_one hε]
    · have h' : ¬ ((n : ℤ) ∣ ((k : ℤ) - (r + (n : ℤ)))) := by
        intro hd
        refine h ?_
        have hsplit : (k : ℤ) - r = ((k : ℤ) - (r + (n : ℤ))) + (n : ℤ) := by ring
        rw [hsplit]
        exact dvd_add hd dvd_rfl
      simp [coef, h, h']
  simp only [F, key, Finset.mul_sum, mul_assoc]

lemma F_sub_natCast (n : ℕ) {ε : ℤ} (hε : ε * ε = 1) (hn : 0 < n) (r : ℤ) (m : ℕ) :
    F n ε (r - n) m = ε * F n ε r m := by
  have h := F_add_natCast n hε hn (r - n) m
  have hr : r - (n : ℤ) + (n : ℤ) = r := by ring
  rw [hr] at h
  rw [h, ← mul_assoc, hε, one_mul]

/-- `H_{-(s-1)}(m,n) = H_{n-s+1}(m,n)`, the first half of (10). -/
theorem H_add_natCast (n : ℕ) (hn : 0 < n) (r : ℤ) (m : ℕ) : H n (r + n) m = H n r m := by
  simpa [H] using F_add_natCast n (ε := 1) (by norm_num) hn r m

/-- `K_{-(s-1)}(m,n) = -K_{n-s+1}(m,n)`, the second half of (10). -/
theorem K_add_natCast (n : ℕ) (hn : 0 < n) (r : ℤ) (m : ℕ) : K n (r + n) m = - K n r m := by
  simpa [K] using F_add_natCast n (ε := -1) (by norm_num) hn r m

/-- The wrap-around equation `Δ y₁ = yₙ` of Definition 3: together with `F_succ`
(which is `Δ y_s = y_{s-1}` for `s = 2, …, n`) and the initial values `F_zero_nat`,
this shows that `H n 0, …, H n (n-1)` solve the difference system (6). -/
theorem H_delta_one (n : ℕ) (hn : 0 < n) (m : ℕ) :
    H n 0 (m + 1) = H n 0 m + H n ((n : ℤ) - 1) m := by
  have hper : H n ((n : ℤ) - 1) m = H n (-1) m := by
    have h := H_add_natCast n hn (-1) m
    rwa [show (-1 : ℤ) + (n : ℤ) = (n : ℤ) - 1 by ring] at h
  rw [hper]
  simpa [H] using F_succ n 1 0 m

/-- The wrap-around equation `Δ y₁ = -yₙ` of Definition 4: together with `F_succ` and
`F_zero_nat`, this shows that `K n 0, …, K n (n-1)` solve the difference system (7). -/
theorem K_delta_one (n : ℕ) (hn : 0 < n) (m : ℕ) :
    K n 0 (m + 1) = K n 0 m - K n ((n : ℤ) - 1) m := by
  have hper : K n ((n : ℤ) - 1) m = - K n (-1) m := by
    have h := K_add_natCast n hn (-1) m
    rwa [show (-1 : ℤ) + (n : ℤ) = (n : ℤ) - 1 by ring] at h
  rw [hper, sub_neg_eq_add]
  simpa [K] using F_succ n (-1) 0 m

/-! ## 4. Theorem 1: the closed formulas (8) and (9)

Formulas (18) and (19) of the paper are proved here by the root-of-unity filter,
which is the content of `sum_zpow_eq` (for `x^n = 1`) and `sum_zpow_odd`
(for `x^n = -1`, where the paper uses the roots `μ, μ^3, …, μ^{2n-1}`). -/

/-- Root-of-unity filter: `∑_{j<n} ζ^{ja} = n` if `n ∣ a`, and `0` otherwise. -/
lemma sum_zpow_eq (n : ℕ) (hn : 0 < n) {ζ : ℂ} (hζ : IsPrimitiveRoot ζ n) (a : ℤ) :
    ∑ j ∈ range n, ζ ^ ((j : ℤ) * a) = if (n : ℤ) ∣ a then (n : ℂ) else 0 := by
  have hζ0 : ζ ≠ 0 := hζ.ne_zero hn.ne'
  have hx : ∀ j : ℕ, ζ ^ ((j : ℤ) * a) = (ζ ^ a) ^ j := by
    intro j
    rw [mul_comm, zpow_mul, ← zpow_natCast (ζ ^ a) j]
  simp only [hx]
  by_cases h : (n : ℤ) ∣ a
  · have h1 : ζ ^ a = 1 := (hζ.zpow_eq_one_iff_dvd a).mpr h
    simp [h1, h]
  · have h1 : ζ ^ a ≠ 1 := fun hc => h ((hζ.zpow_eq_one_iff_dvd a).mp hc)
    have h2 : (ζ ^ a) ^ n = 1 := by
      rw [← zpow_natCast (ζ ^ a) n, ← zpow_mul, mul_comm, zpow_mul,
        zpow_natCast, hζ.pow_eq_one, one_zpow]
    rw [geom_sum_eq h1, h2, sub_self, zero_div, if_neg h]

/-- `(-1 : ℂ) ^ t = mark (-1) t` for every integer `t`. -/
lemma negOne_zpow_eq_mark (t : ℤ) : ((-1 : ℂ)) ^ t = ((mark (-1) t : ℤ) : ℂ) := by
  rcases Int.even_or_odd t with h | h
  · rw [h.neg_one_zpow, mark, if_pos h]; norm_num
  · have h' : ¬ Even t := by simpa [Int.not_even_iff_odd] using h
    rw [h.neg_one_zpow, mark, if_neg h']; norm_num

/-- Filter along the `n`-th roots of `-1`, i.e. along `μ^{2j+1}` where `μ^n = -1`.
This is what produces the sign `(-1)^t` of formula (9). -/
lemma sum_zpow_odd (n : ℕ) (hn : 0 < n) {μ : ℂ} (hμ0 : μ ≠ 0) (hμn : μ ^ n = -1)
    (hμ2 : IsPrimitiveRoot (μ ^ 2) n) (a : ℤ) :
    ∑ j ∈ range n, μ ^ ((2 * (j : ℤ) + 1) * a)
      = if (n : ℤ) ∣ a then (n : ℂ) * ((mark (-1) (a / (n : ℤ)) : ℤ) : ℂ) else 0 := by
  have hsplit : ∀ j : ℕ, μ ^ ((2 * (j : ℤ) + 1) * a) = μ ^ a * (μ ^ 2) ^ ((j : ℤ) * a) := by
    intro j
    rw [← zpow_natCast μ 2, ← zpow_mul, ← zpow_add₀ hμ0]
    congr 1
    ring
  rw [Finset.sum_congr rfl (fun j _ => hsplit j), ← Finset.mul_sum,
    sum_zpow_eq n hn hμ2 a]
  by_cases h : (n : ℤ) ∣ a
  · obtain ⟨t, ht⟩ := h
    have hdiv : a / (n : ℤ) = t := by
      rw [ht, Int.mul_ediv_cancel_left]
      exact_mod_cast hn.ne'
    have hμa : μ ^ a = ((-1 : ℂ)) ^ t := by
      rw [ht, zpow_mul, zpow_natCast, hμn]
    rw [if_pos ⟨t, ht⟩, if_pos ⟨t, ht⟩, hμa, negOne_zpow_eq_mark, hdiv]
    ring
  · rw [if_neg h, if_neg h, mul_zero]

/-- **Theorem 1, formula (8)** (paper's (18)), in the form without division:
`n * H_s(m,n) = ∑_{j<n} (ζ^j + 1)^m ζ^{-j(s-1)}` for any primitive `n`-th root `ζ`. -/
theorem theorem1_H (n : ℕ) (hn : 0 < n) {ζ : ℂ} (hζ : IsPrimitiveRoot ζ n) (r : ℤ) (m : ℕ) :
    (n : ℂ) * ((H n r m : ℤ) : ℂ)
      = ∑ j ∈ range n, (ζ ^ j + 1) ^ m * ζ ^ (-((j : ℤ) * r)) := by
  have hζ0 : ζ ≠ 0 := hζ.ne_zero hn.ne'
  have hpow : ∀ j k : ℕ, (ζ ^ j) ^ k = ζ ^ ((j : ℤ) * (k : ℤ)) := by
    intro j k
    rw [← pow_mul, ← zpow_natCast ζ (j * k)]
    norm_cast
  have expand : ∀ j : ℕ, (ζ ^ j + 1) ^ m * ζ ^ (-((j : ℤ) * r))
      = ∑ k ∈ range (m + 1), (m.choose k : ℂ) * ζ ^ ((j : ℤ) * ((k : ℤ) - r)) := by
    intro j
    rw [add_pow, Finset.sum_mul]
    refine Finset.sum_congr rfl fun k _ => ?_
    rw [one_pow, mul_one, hpow]
    rw [show ζ ^ ((j : ℤ) * (k : ℤ)) * (m.choose k : ℂ) * ζ ^ (-((j : ℤ) * r))
          = (m.choose k : ℂ) * (ζ ^ ((j : ℤ) * (k : ℤ)) * ζ ^ (-((j : ℤ) * r))) by ring,
      ← zpow_add₀ hζ0]
    congr 2
    ring
  have hHcast : ((H n r m : ℤ) : ℂ)
      = ∑ k ∈ range (m + 1), (if (n : ℤ) ∣ ((k : ℤ) - r) then (m.choose k : ℂ) else 0) := by
    rw [H_eq]
    push_cast
    refine Finset.sum_congr rfl fun k _ => ?_
    split_ifs <;> simp
  refine Eq.symm ?_
  calc ∑ j ∈ range n, (ζ ^ j + 1) ^ m * ζ ^ (-((j : ℤ) * r))
      = ∑ j ∈ range n, ∑ k ∈ range (m + 1), (m.choose k : ℂ) * ζ ^ ((j : ℤ) * ((k : ℤ) - r)) :=
        Finset.sum_congr rfl fun j _ => expand j
    _ = ∑ k ∈ range (m + 1), ∑ j ∈ range n, (m.choose k : ℂ) * ζ ^ ((j : ℤ) * ((k : ℤ) - r)) :=
        Finset.sum_comm
    _ = ∑ k ∈ range (m + 1),
          (m.choose k : ℂ) * (if (n : ℤ) ∣ ((k : ℤ) - r) then (n : ℂ) else 0) := by
        refine Finset.sum_congr rfl fun k _ => ?_
        rw [← Finset.mul_sum, sum_zpow_eq n hn hζ]
    _ = (n : ℂ) * ((H n r m : ℤ) : ℂ) := by
        rw [hHcast, Finset.mul_sum]
        refine Finset.sum_congr rfl fun k _ => ?_
        split_ifs <;> ring

/-- The divided form of formula (8), as printed in the paper. -/
theorem theorem1_H' (n : ℕ) (hn : 0 < n) {ζ : ℂ} (hζ : IsPrimitiveRoot ζ n) (r : ℤ) (m : ℕ) :
    ((H n r m : ℤ) : ℂ)
      = (n : ℂ)⁻¹ * ∑ j ∈ range n, (ζ ^ j + 1) ^ m * ζ ^ (-((j : ℤ) * r)) := by
  have hn0 : (n : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr hn.ne'
  rw [← theorem1_H n hn hζ r m, ← mul_assoc, inv_mul_cancel₀ hn0, one_mul]

/-- **Theorem 1, formula (9)** (paper's (19)), in the form without division.
Here `μ` plays the role of `exp(πi/n)`: `μ^n = -1` and `μ^2` is a primitive `n`-th root
of unity, so `{μ^{2j+1}}_{j<n}` are exactly the `n` roots of `x^n = -1`. -/
theorem theorem1_K (n : ℕ) (hn : 0 < n) {μ : ℂ} (hμ0 : μ ≠ 0) (hμn : μ ^ n = -1)
    (hμ2 : IsPrimitiveRoot (μ ^ 2) n) (r : ℤ) (m : ℕ) :
    (n : ℂ) * ((K n r m : ℤ) : ℂ)
      = ∑ j ∈ range n, (μ ^ (2 * j + 1) + 1) ^ m * μ ^ (-((2 * (j : ℤ) + 1) * r)) := by
  have hpow : ∀ j k : ℕ, (μ ^ (2 * j + 1)) ^ k = μ ^ ((2 * (j : ℤ) + 1) * (k : ℤ)) := by
    intro j k
    rw [← pow_mul, ← zpow_natCast μ ((2 * j + 1) * k)]
    push_cast
    ring_nf
  have expand : ∀ j : ℕ, (μ ^ (2 * j + 1) + 1) ^ m * μ ^ (-((2 * (j : ℤ) + 1) * r))
      = ∑ k ∈ range (m + 1), (m.choose k : ℂ) * μ ^ ((2 * (j : ℤ) + 1) * ((k : ℤ) - r)) := by
    intro j
    rw [add_pow, Finset.sum_mul]
    refine Finset.sum_congr rfl fun k _ => ?_
    rw [one_pow, mul_one, hpow]
    rw [show μ ^ ((2 * (j : ℤ) + 1) * (k : ℤ)) * (m.choose k : ℂ)
            * μ ^ (-((2 * (j : ℤ) + 1) * r))
          = (m.choose k : ℂ) * (μ ^ ((2 * (j : ℤ) + 1) * (k : ℤ))
            * μ ^ (-((2 * (j : ℤ) + 1) * r))) by ring,
      ← zpow_add₀ hμ0]
    congr 2
    ring
  have hKcast : ((K n r m : ℤ) : ℂ)
      = ∑ k ∈ range (m + 1),
          (if (n : ℤ) ∣ ((k : ℤ) - r)
            then ((mark (-1) (((k : ℤ) - r) / (n : ℤ)) : ℤ) : ℂ) * (m.choose k : ℂ) else 0) := by
    rw [K, F]
    push_cast
    refine Finset.sum_congr rfl fun k _ => ?_
    simp only [coef]
    split_ifs <;> push_cast <;> ring
  refine Eq.symm ?_
  calc ∑ j ∈ range n, (μ ^ (2 * j + 1) + 1) ^ m * μ ^ (-((2 * (j : ℤ) + 1) * r))
      = ∑ j ∈ range n, ∑ k ∈ range (m + 1),
          (m.choose k : ℂ) * μ ^ ((2 * (j : ℤ) + 1) * ((k : ℤ) - r)) :=
        Finset.sum_congr rfl fun j _ => expand j
    _ = ∑ k ∈ range (m + 1), ∑ j ∈ range n,
          (m.choose k : ℂ) * μ ^ ((2 * (j : ℤ) + 1) * ((k : ℤ) - r)) := Finset.sum_comm
    _ = ∑ k ∈ range (m + 1), (m.choose k : ℂ) *
          (if (n : ℤ) ∣ ((k : ℤ) - r)
            then (n : ℂ) * ((mark (-1) (((k : ℤ) - r) / (n : ℤ)) : ℤ) : ℂ) else 0) := by
        refine Finset.sum_congr rfl fun k _ => ?_
        rw [← Finset.mul_sum, sum_zpow_odd n hn hμ0 hμn hμ2]
    _ = (n : ℂ) * ((K n r m : ℤ) : ℂ) := by
        rw [hKcast, Finset.mul_sum]
        refine Finset.sum_congr rfl fun k _ => ?_
        split_ifs <;> ring

/-- The divided form of formula (9), as printed in the paper. -/
theorem theorem1_K' (n : ℕ) (hn : 0 < n) {μ : ℂ} (hμ0 : μ ≠ 0) (hμn : μ ^ n = -1)
    (hμ2 : IsPrimitiveRoot (μ ^ 2) n) (r : ℤ) (m : ℕ) :
    ((K n r m : ℤ) : ℂ)
      = (n : ℂ)⁻¹ * ∑ j ∈ range n, (μ ^ (2 * j + 1) + 1) ^ m * μ ^ (-((2 * (j : ℤ) + 1) * r)) := by
  have hn0 : (n : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr hn.ne'
  rw [← theorem1_K n hn hμ0 hμn hμ2 r m, ← mul_assoc, inv_mul_cancel₀ hn0, one_mul]

/-! ### The paper's concrete roots

Formulas (8) and (9) exactly as printed, with `ω = exp(2πi/n)` and `μ = exp(πi/n)`. -/

open Complex in
/-- **Formula (8)** with the paper's `ω = exp(2πi/n)`. -/
theorem theorem1_H_exp (n : ℕ) (hn : 0 < n) (r : ℤ) (m : ℕ) :
    ((H n r m : ℤ) : ℂ)
      = (n : ℂ)⁻¹ * ∑ j ∈ range n,
          (exp (2 * Real.pi * I / n) ^ j + 1) ^ m
            * exp (2 * Real.pi * I / n) ^ (-((j : ℤ) * r)) :=
  theorem1_H' n hn (Complex.isPrimitiveRoot_exp n hn.ne') r m

open Complex in
/-- **Formula (9)** with the paper's `μ = exp(πi/n)`: indeed `μ ≠ 0`, `μ ^ n = -1`, and
`μ ^ 2 = exp(2πi/n)` is a primitive `n`-th root of unity, so `theorem1_K'` applies. -/
theorem theorem1_K_exp (n : ℕ) (hn : 0 < n) (r : ℤ) (m : ℕ) :
    ((K n r m : ℤ) : ℂ)
      = (n : ℂ)⁻¹ * ∑ j ∈ range n,
          (exp (Real.pi * I / n) ^ (2 * j + 1) + 1) ^ m
            * exp (Real.pi * I / n) ^ (-((2 * (j : ℤ) + 1) * r)) := by
  have hn' : (n : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr hn.ne'
  have hμn : exp (Real.pi * I / n) ^ n = -1 := by
    rw [← Complex.exp_nat_mul,
      show (n : ℂ) * (Real.pi * I / n) = Real.pi * I by field_simp,
      Complex.exp_pi_mul_I]
  have hμ2 : IsPrimitiveRoot (exp (Real.pi * I / n) ^ 2) n := by
    rw [← Complex.exp_nat_mul,
      show ((2 : ℕ) : ℂ) * (Real.pi * I / n) = 2 * Real.pi * I / n by push_cast; ring]
    exact Complex.isPrimitiveRoot_exp n hn.ne'
  exact theorem1_K' n hn (Complex.exp_ne_zero _) hμn hμ2 r m
/-! ## 6. Sanity checks and the paper's examples

`H 3 0 5 = C(5,0) + C(5,3) = 11`, matching `H_1(m,3) = (2^m + 2 cos(πm/3))/3`
(A024493); `K 2 1` is A009545, the difference analog of `sin`; `H 2 0` is the
analog of `cosh`. Everything is computable, so the checks are by `decide`. -/

example : H 3 0 5 = 11 ∧ H 3 1 5 = 10 ∧ H 3 2 5 = 11 := by decide

example : (List.range 8).map (K 2 1) = [0, 1, 2, 2, 0, -4, -8, -8] := by decide

example : (List.range 6).map (H 2 0) = [1, 1, 2, 4, 8, 16] := by decide

/-! ## 6. Bridge goals: Theorem 1's formulas as direct consequences

Theorem 1 is formalized above under our index-shifted convention (r = s - 1).
These bridge goals state the paper's formulas *exactly as printed*, with the
paper's original indexing, and ask Leanstral to derive them from our API.
-/

theorem paper_theorem_1_H (n : ℕ) (hn : 0 < n) {ζ : ℂ} (hζ : IsPrimitiveRoot ζ n)
    (m : ℕ) (s : ℕ) (hs : 1 ≤ s) (hs' : s ≤ n) :
    ((H n ((s : ℤ) - 1) m : ℤ) : ℂ)
      = (n : ℂ)⁻¹ * ∑ j ∈ range n, (ζ ^ j + 1) ^ m * ζ ^ (-((j : ℤ) * ((s : ℤ) - 1))) := by
  sorry

theorem paper_theorem_1_K (n : ℕ) (hn : 0 < n) {μ : ℂ} (hμ0 : μ ≠ 0) (hμn : μ ^ n = -1)
    (hμ2 : IsPrimitiveRoot (μ ^ 2) n) (m : ℕ) (s : ℕ) (hs : 1 ≤ s) (hs' : s ≤ n) :
    ((K n ((s : ℤ) - 1) m : ℤ) : ℂ)
      = (n : ℂ)⁻¹ * ∑ j ∈ range n,
          (μ ^ (2 * j + 1) + 1) ^ m * μ ^ (-((2 * (j : ℤ) + 1) * ((s : ℤ) - 1))) := by
  sorry

end Shevelev
