import Mathlib

-- This is a standalone project rather than a Mathlib file, so it carries no
-- Mathlib copyright header; the rest of the `mathlibStandardSet` linters are on.
set_option linter.style.header false

/-!
# Combinatorial identities from difference analogs of hyperbolic and trigonometric functions

A Lean 4 / Mathlib formalization of

  Vladimir Shevelev, *Combinatorial identities generated by difference analogs of
  hyperbolic and trigonometric functions of order n*, arXiv:1706.01454v4 [math.CO].

**Index convention:** indices are shifted by one (`r = s - 1`):
- `H n r m` is the paper's `H_{r+1}(m,n)`  (formula (13))
- `K n r m` is the paper's `K_{r+1}(m,n)`  (formula (14))

**Theorem 1** (formulas (8) and (9): closed formulas via root-of-unity filters) is
formalized sorry-free with Lean 4.30.0 / Mathlib v4.30.0. Two bridge goals at
the end restate the paper's exact printed formulas and are left as `sorry`.
-/
namespace Shevelev

open Finset


def mark (ε : ℤ) (q : ℤ) : ℤ := if Even q then 1 else ε

@[simp] lemma mark_zero (ε : ℤ) : mark ε 0 = 1 := by simp [mark]

@[simp] lemma mark_one_eq (q : ℤ) : mark 1 q = 1 := by
  unfold mark; split <;> rfl


def coef (n : ℕ) (ε : ℤ) (r : ℤ) (k : ℕ) : ℤ :=
  if (n : ℤ) ∣ ((k : ℤ) - r) then mark ε (((k : ℤ) - r) / (n : ℤ)) else 0

def F (n : ℕ) (ε : ℤ) (r : ℤ) (m : ℕ) : ℤ :=
  ∑ k ∈ range (m + 1), coef n ε r k * (m.choose k : ℤ)

def H (n : ℕ) (r : ℤ) (m : ℕ) : ℤ := F n 1 r m

def K (n : ℕ) (r : ℤ) (m : ℕ) : ℤ := F n (-1) r m

lemma H_eq (n : ℕ) (r : ℤ) (m : ℕ) :
    H n r m = ∑ k ∈ range (m + 1), (if (n : ℤ) ∣ ((k : ℤ) - r) then (m.choose k : ℤ) else 0) := by
  rw [H, F]
  refine Finset.sum_congr rfl fun k _ => ?_
  simp only [coef, mark_one_eq]
  split_ifs <;> ring

/-! ## 3. Theorem 1: the closed formulas (8) and (9)

Formulas (18) and (19) of the paper are proved here by the root-of-unity filter,
which is the content of `sum_zpow_eq` (for `x^n = 1`) and `sum_zpow_odd`
(for `x^n = -1`, where the paper uses the roots `μ, μ^3, …, μ^{2n-1}`). -/

/-- Root-of-unity filter: `∑_{j<n} ζ^{ja} = n` if `n ∣ a`, and `0` otherwise. -/
lemma sum_zpow_eq (n : ℕ) (hn : 0 < n) {ζ : ℂ} (hζ : IsPrimitiveRoot ζ n) (a : ℤ) :
    ∑ j ∈ range n, ζ ^ ((j : ℤ) * a) = if (n : ℤ) ∣ a then (n : ℂ) else 0 := by
  have hζ0 : ζ ≠ 0 := hζ.ne_zero hn.ne'
  have hx : ∀ j : ℕ, ζ ^ ((j : ℤ) * a) = (ζ ^ a) ^ j := by
    intro j
    rw [mul_comm, zpow_mul, ← zpow_natCast (ζ ^ a) j]
  simp only [hx]
  by_cases h : (n : ℤ) ∣ a
  · have h1 : ζ ^ a = 1 := (hζ.zpow_eq_one_iff_dvd a).mpr h
    simp [h1, h]
  · have h1 : ζ ^ a ≠ 1 := fun hc => h ((hζ.zpow_eq_one_iff_dvd a).mp hc)
    have h2 : (ζ ^ a) ^ n = 1 := by
      rw [← zpow_natCast (ζ ^ a) n, ← zpow_mul, mul_comm, zpow_mul,
        zpow_natCast, hζ.pow_eq_one, one_zpow]
    rw [geom_sum_eq h1, h2, sub_self, zero_div, if_neg h]

/-- `(-1 : ℂ) ^ t = mark (-1) t` for every integer `t`. -/
lemma negOne_zpow_eq_mark (t : ℤ) : ((-1 : ℂ)) ^ t = ((mark (-1) t : ℤ) : ℂ) := by
  rcases Int.even_or_odd t with h | h
  · rw [h.neg_one_zpow, mark, if_pos h]; norm_num
  · have h' : ¬ Even t := by simpa [Int.not_even_iff_odd] using h
    rw [h.neg_one_zpow, mark, if_neg h']; norm_num

/-- Filter along the `n`-th roots of `-1`, i.e. along `μ^{2j+1}` where `μ^n = -1`.
This is what produces the sign `(-1)^t` of formula (9). -/
lemma sum_zpow_odd (n : ℕ) (hn : 0 < n) {μ : ℂ} (hμ0 : μ ≠ 0) (hμn : μ ^ n = -1)
    (hμ2 : IsPrimitiveRoot (μ ^ 2) n) (a : ℤ) :
    ∑ j ∈ range n, μ ^ ((2 * (j : ℤ) + 1) * a)
      = if (n : ℤ) ∣ a then (n : ℂ) * ((mark (-1) (a / (n : ℤ)) : ℤ) : ℂ) else 0 := by
  have hsplit : ∀ j : ℕ, μ ^ ((2 * (j : ℤ) + 1) * a) = μ ^ a * (μ ^ 2) ^ ((j : ℤ) * a) := by
    intro j
    rw [← zpow_natCast μ 2, ← zpow_mul, ← zpow_add₀ hμ0]
    congr 1
    ring
  rw [Finset.sum_congr rfl (fun j _ => hsplit j), ← Finset.mul_sum,
    sum_zpow_eq n hn hμ2 a]
  by_cases h : (n : ℤ) ∣ a
  · obtain ⟨t, ht⟩ := h
    have hdiv : a / (n : ℤ) = t := by
      rw [ht, Int.mul_ediv_cancel_left]
      exact_mod_cast hn.ne'
    have hμa : μ ^ a = ((-1 : ℂ)) ^ t := by
      rw [ht, zpow_mul, zpow_natCast, hμn]
    rw [if_pos ⟨t, ht⟩, if_pos ⟨t, ht⟩, hμa, negOne_zpow_eq_mark, hdiv]
    ring
  · rw [if_neg h, if_neg h, mul_zero]

/-- **Theorem 1, formula (8)** (paper's (18)), in the form without division:
`n * H_s(m,n) = ∑_{j<n} (ζ^j + 1)^m ζ^{-j(s-1)}` for any primitive `n`-th root `ζ`. -/
theorem theorem1_H (n : ℕ) (hn : 0 < n) {ζ : ℂ} (hζ : IsPrimitiveRoot ζ n) (r : ℤ) (m : ℕ) :
    (n : ℂ) * ((H n r m : ℤ) : ℂ)
      = ∑ j ∈ range n, (ζ ^ j + 1) ^ m * ζ ^ (-((j : ℤ) * r)) := by
  have hζ0 : ζ ≠ 0 := hζ.ne_zero hn.ne'
  have hpow : ∀ j k : ℕ, (ζ ^ j) ^ k = ζ ^ ((j : ℤ) * (k : ℤ)) := by
    intro j k
    rw [← pow_mul, ← zpow_natCast ζ (j * k)]
    norm_cast
  have expand : ∀ j : ℕ, (ζ ^ j + 1) ^ m * ζ ^ (-((j : ℤ) * r))
      = ∑ k ∈ range (m + 1), (m.choose k : ℂ) * ζ ^ ((j : ℤ) * ((k : ℤ) - r)) := by
    intro j
    rw [add_pow, Finset.sum_mul]
    refine Finset.sum_congr rfl fun k _ => ?_
    rw [one_pow, mul_one, hpow]
    rw [show ζ ^ ((j : ℤ) * (k : ℤ)) * (m.choose k : ℂ) * ζ ^ (-((j : ℤ) * r))
          = (m.choose k : ℂ) * (ζ ^ ((j : ℤ) * (k : ℤ)) * ζ ^ (-((j : ℤ) * r))) by ring,
      ← zpow_add₀ hζ0]
    congr 2
    ring
  have hHcast : ((H n r m : ℤ) : ℂ)
      = ∑ k ∈ range (m + 1), (if (n : ℤ) ∣ ((k : ℤ) - r) then (m.choose k : ℂ) else 0) := by
    rw [H_eq]
    push_cast
    refine Finset.sum_congr rfl fun k _ => ?_
    split_ifs <;> simp
  refine Eq.symm ?_
  calc ∑ j ∈ range n, (ζ ^ j + 1) ^ m * ζ ^ (-((j : ℤ) * r))
      = ∑ j ∈ range n, ∑ k ∈ range (m + 1), (m.choose k : ℂ) * ζ ^ ((j : ℤ) * ((k : ℤ) - r)) :=
        Finset.sum_congr rfl fun j _ => expand j
    _ = ∑ k ∈ range (m + 1), ∑ j ∈ range n, (m.choose k : ℂ) * ζ ^ ((j : ℤ) * ((k : ℤ) - r)) :=
        Finset.sum_comm
    _ = ∑ k ∈ range (m + 1),
          (m.choose k : ℂ) * (if (n : ℤ) ∣ ((k : ℤ) - r) then (n : ℂ) else 0) := by
        refine Finset.sum_congr rfl fun k _ => ?_
        rw [← Finset.mul_sum, sum_zpow_eq n hn hζ]
    _ = (n : ℂ) * ((H n r m : ℤ) : ℂ) := by
        rw [hHcast, Finset.mul_sum]
        refine Finset.sum_congr rfl fun k _ => ?_
        split_ifs <;> ring

/-- **Theorem 1, formula (9)** (paper's (19)), in the form without division.
Here `μ` plays the role of `exp(πi/n)`: `μ^n = -1` and `μ^2` is a primitive `n`-th root
of unity, so `{μ^{2j+1}}_{j<n}` are exactly the `n` roots of `x^n = -1`. -/
theorem theorem1_K (n : ℕ) (hn : 0 < n) {μ : ℂ} (hμ0 : μ ≠ 0) (hμn : μ ^ n = -1)
    (hμ2 : IsPrimitiveRoot (μ ^ 2) n) (r : ℤ) (m : ℕ) :
    (n : ℂ) * ((K n r m : ℤ) : ℂ)
      = ∑ j ∈ range n, (μ ^ (2 * j + 1) + 1) ^ m * μ ^ (-((2 * (j : ℤ) + 1) * r)) := by
  have hpow : ∀ j k : ℕ, (μ ^ (2 * j + 1)) ^ k = μ ^ ((2 * (j : ℤ) + 1) * (k : ℤ)) := by
    intro j k
    rw [← pow_mul, ← zpow_natCast μ ((2 * j + 1) * k)]
    push_cast
    ring_nf
  have expand : ∀ j : ℕ, (μ ^ (2 * j + 1) + 1) ^ m * μ ^ (-((2 * (j : ℤ) + 1) * r))
      = ∑ k ∈ range (m + 1), (m.choose k : ℂ) * μ ^ ((2 * (j : ℤ) + 1) * ((k : ℤ) - r)) := by
    intro j
    rw [add_pow, Finset.sum_mul]
    refine Finset.sum_congr rfl fun k _ => ?_
    rw [one_pow, mul_one, hpow]
    rw [show μ ^ ((2 * (j : ℤ) + 1) * (k : ℤ)) * (m.choose k : ℂ)
            * μ ^ (-((2 * (j : ℤ) + 1) * r))
          = (m.choose k : ℂ) * (μ ^ ((2 * (j : ℤ) + 1) * (k : ℤ))
            * μ ^ (-((2 * (j : ℤ) + 1) * r))) by ring,
      ← zpow_add₀ hμ0]
    congr 2
    ring
  have hKcast : ((K n r m : ℤ) : ℂ)
      = ∑ k ∈ range (m + 1),
          (if (n : ℤ) ∣ ((k : ℤ) - r)
            then ((mark (-1) (((k : ℤ) - r) / (n : ℤ)) : ℤ) : ℂ) * (m.choose k : ℂ) else 0) := by
    rw [K, F]
    push_cast
    refine Finset.sum_congr rfl fun k _ => ?_
    simp only [coef]
    split_ifs <;> push_cast <;> ring
  refine Eq.symm ?_
  calc ∑ j ∈ range n, (μ ^ (2 * j + 1) + 1) ^ m * μ ^ (-((2 * (j : ℤ) + 1) * r))
      = ∑ j ∈ range n, ∑ k ∈ range (m + 1),
          (m.choose k : ℂ) * μ ^ ((2 * (j : ℤ) + 1) * ((k : ℤ) - r)) :=
        Finset.sum_congr rfl fun j _ => expand j
    _ = ∑ k ∈ range (m + 1), ∑ j ∈ range n,
          (m.choose k : ℂ) * μ ^ ((2 * (j : ℤ) + 1) * ((k : ℤ) - r)) := Finset.sum_comm
    _ = ∑ k ∈ range (m + 1), (m.choose k : ℂ) *
          (if (n : ℤ) ∣ ((k : ℤ) - r)
            then (n : ℂ) * ((mark (-1) (((k : ℤ) - r) / (n : ℤ)) : ℤ) : ℂ) else 0) := by
        refine Finset.sum_congr rfl fun k _ => ?_
        rw [← Finset.mul_sum, sum_zpow_odd n hn hμ0 hμn hμ2]
    _ = (n : ℂ) * ((K n r m : ℤ) : ℂ) := by
        rw [hKcast, Finset.mul_sum]
        refine Finset.sum_congr rfl fun k _ => ?_
        split_ifs <;> ring

/-! ### The paper's concrete roots

Formulas (8) and (9) exactly as printed, with `ω = exp(2πi/n)` and `μ = exp(πi/n)`. -/

open Complex in
/-- **Formula (8)** — closed form with `ω = exp(2πi/n)`. -/
theorem theorem1_H_exp (n : ℕ) (hn : 0 < n) (r : ℤ) (m : ℕ) :
    ((H n r m : ℤ) : ℂ)
      = (n : ℂ)⁻¹ * ∑ j ∈ range n,
          (exp (2 * Real.pi * I / n) ^ j + 1) ^ m
            * exp (2 * Real.pi * I / n) ^ (-((j : ℤ) * r)) := by
  have hn0 : (n : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr hn.ne'
  rw [← theorem1_H n hn (Complex.isPrimitiveRoot_exp n hn.ne') r m, ← mul_assoc, inv_mul_cancel₀ hn0, one_mul]

open Complex in
/-- **Formula (9)** — closed form with `μ = exp(πi/n)`. -/
theorem theorem1_K_exp (n : ℕ) (hn : 0 < n) (r : ℤ) (m : ℕ) :
    ((K n r m : ℤ) : ℂ)
      = (n : ℂ)⁻¹ * ∑ j ∈ range n,
          (exp (Real.pi * I / n) ^ (2 * j + 1) + 1) ^ m
            * exp (Real.pi * I / n) ^ (-((2 * (j : ℤ) + 1) * r)) := by
  have hn0 : (n : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr hn.ne'
  have hμn : exp (Real.pi * I / n) ^ n = -1 := by
    rw [← Complex.exp_nat_mul,
      show (n : ℂ) * (Real.pi * I / n) = Real.pi * I by field_simp,
      Complex.exp_pi_mul_I]
  have hμ2 : IsPrimitiveRoot (exp (Real.pi * I / n) ^ 2) n := by
    rw [← Complex.exp_nat_mul,
      show ((2 : ℕ) : ℂ) * (Real.pi * I / n) = 2 * Real.pi * I / n by push_cast; ring]
    exact Complex.isPrimitiveRoot_exp n hn.ne'
  have key := theorem1_K n hn (Complex.exp_ne_zero _) hμn hμ2 r m
  rw [← key, ← mul_assoc, inv_mul_cancel₀ hn0, one_mul]

end Shevelev
